apiVersion: apps/v1
kind: Deployment
metadata:
  name: adea-redis
  labels:
    app: adea
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adea
      component: redis
  template:
    metadata:
      labels:
        app: adea
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: adea-redis
  labels:
    app: adea
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: adea
    component: redis